import { apiUrl } from "../apiSettings";

const locationActivities =
  "&populate[locationActivities][populate][activity][populate][activityInfo]=*";
const extraPartyList =
  "&populate[escapeGameParty][populate][linkedActivity][populate][activityInfo]=*&populate[escapeGameParty][populate][activityListImage][fields][0]=name&populate[escapeGameParty][populate][activityListImage][fields][1]=url&populate[escapeGameParty][populate][activityListImage][fields][2]=alternativeText&populate[escapeGameParty][populate][activityListImage][fields][3]=width&populate[escapeGameParty][populate][activityListImage][fields][4]=height";
const extraPartySlider =
  "&populate[escapeGameParty][populate][sliderImage][fields][0]=name&populate[escapeGameParty][populate][sliderImage][fields][1]=url&populate[escapeGameParty][populate][sliderImage][fields][2]=alternativeText&populate[escapeGameParty][populate][sliderImage][fields][3]=width&populate[escapeGameParty][populate][sliderImage][fields][4]=height&populate[escapeGameParty][populate][price]=*";
const extraPartyCardImage =
  "&populate[escapeGameParty][populate][partyCardImage][fields][0]=name&populate[escapeGameParty][populate][partyCardImage][fields][1]=url&populate[escapeGameParty][populate][partyCardImage][fields][2]=alternativeText&populate[escapeGameParty][populate][partyCardImage][fields][3]=width&populate[escapeGameParty][populate][partyCardImage][fields][4]=height";

export const locationSlugListQuery =
  apiUrl +
  "locations?populate[locationInfo]=*&populate[bookingInfo]=*" +
  locationActivities +
  extraPartyList +
  "&sort[0]=priority:asc";
//const bookingInfo = "&populate[bookingInfo]=*";

export const allActivitiesSluglistQuery =
  apiUrl + "activities?populate[activityInfo]=*&sort[0]=priority:asc";

export const allEventsSluglistQuery = apiUrl + "events?sort[0]=priority:asc";

const obj = {
  id: 2,
  attributes: {
    createdAt: "2024-01-24T13:43:51.080Z",
    updatedAt: "2026-05-20T20:02:58.695Z",
    publishedAt: "2024-01-24T14:51:28.412Z",
    locationName: "Albany, NY",
    slug: "albany-ny",
    priority: 1,
    isPublished: true,
    locationInfo: {
      id: 2,
      cityName: "Albany",
      state: "New York, NY",
      address: "All In Adventures Escape Rooms 1 Crossgates Mall Rd D212",
      zip: "12203",
      phone: "+1 518-217-5061",
      mall: "Crossgates Mall",
      managerEmail: "mgr103@allinadventures.com",
      storeEmail: "store103@allinadventures.com",
      avgReview: 4.8,
      guestServed: "71k+",
      fivestarId: "4fc2ae1b62734a6e8d9e85cbd613ca0f",
      storeNo: 103,
      raveReviews: "3570+",
      guestCapacity: "2-35",
      catering: "YES",
      privateEvents: "YES",
      parking: "Crossgates Mall Parking ",
      wheelChairAccessibility: true,
      ageRange: "6+",
      locationDescription:
        "<p>Our customers come from many surrounding cities, including Rotterdam, Troy, Clifton Park, Schenectady, Pittsfield and many more!</p>",
      direction:
        "<p>Use the second floor entrance near JCPenney and we are located right across from Banana Republic and next to ZARA.</p>",
      acceptedPayments:
        "<p>We have gone CASHLESS but accept Credit/Debit, PayPal, Venmo, Zelle, Cash App and in some locations Apple Pay and Samsung Pay.</p>",
      text: "+1 518-217-2672",
    },
    bookingInfo: {
      id: 1,
      shortName: "mysteryroom-albany",
      flow: 17838,
      partyPackageItemNo: 44613,
      activePartyPackage: true,
      activeGiftCard: true,
      giftCardItemNo: 360203,
      giftFlow: "no",
      partyPackageFlow: "no",
      playPassItemNo: 571322,
      playPassFlow: "no",
    },
    locationActivities: [
      {
        id: 1,
        bookingItemNo: "44609",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>You are prison guards at Alcatraz and the Warden's keys have gone missing! Can you find them before there is an escape attempt?</p>",
        pageTitle: "ESCAPE FROM ALCATRAZ ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 13,
            attributes: {
              activityName: "Escape From Alcatraz",
              createdAt: "2024-05-17T22:17:44.904Z",
              updatedAt: "2025-07-03T11:14:54.419Z",
              publishedAt: "2024-05-17T22:34:54.713Z",
              activitySlug: "escape-from-alcatraz",
              isPublish: true,
              priority: 1,
              activityInfo: {
                id: 13,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 64,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 2,
        bookingItemNo: "44603",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>You've been captured by a notorious gang of pirates. Prove you're worthy of becoming part of the crew or prepare to walk the plank!</p>",
        pageTitle: "TREASURE ISLAND ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 12,
            attributes: {
              activityName: "Treasure Island",
              createdAt: "2024-05-17T22:02:03.718Z",
              updatedAt: "2025-07-03T11:16:19.860Z",
              publishedAt: "2024-05-17T22:17:13.130Z",
              activitySlug: "treasure-island",
              isPublish: true,
              priority: 2,
              activityInfo: {
                id: 12,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 72,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 5,
        bookingItemNo: "44608",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>Trapped in a lab lockdown with a growing zombie horde, can you develop a vaccine and escape the facility before it is too late?</p>",
        pageTitle: "ZOMBIE APOCALYPSE ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 11,
            attributes: {
              activityName: "Zombie Apocalypse",
              createdAt: "2024-05-17T21:38:36.528Z",
              updatedAt: "2025-07-03T11:18:01.583Z",
              publishedAt: "2024-05-17T21:46:20.352Z",
              activitySlug: "zombie-apocalypse",
              isPublish: true,
              priority: 3,
              activityInfo: {
                id: 11,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 48,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 6,
        bookingItemNo: "44607",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>The great detective Sherlock Holmes has gone missing, but things are not always as they seem. Follow the trail of clues to find him.</p>",
        pageTitle: "SHERLOCK'S LIBRARY ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 10,
            attributes: {
              activityName: "Sherlock's Library",
              createdAt: "2024-05-17T21:15:34.162Z",
              updatedAt: "2025-07-03T11:19:08.321Z",
              publishedAt: "2024-05-17T21:32:43.312Z",
              activitySlug: "sherlocks-library",
              isPublish: true,
              priority: 4,
              activityInfo: {
                id: 10,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 58,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 7,
        bookingItemNo: "44604",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>After acquiring all necessary evidence, it is time to execute your mission. Infiltrate the enemy bunker and apprehend the arms dealer!</p>",
        pageTitle: "BLACK OPS ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 9,
            attributes: {
              activityName: "Black Ops",
              createdAt: "2024-05-17T20:55:34.096Z",
              updatedAt: "2025-07-03T13:38:47.512Z",
              publishedAt: "2024-05-17T21:14:38.587Z",
              activitySlug: "black-ops",
              isPublish: true,
              priority: 5,
              activityInfo: {
                id: 9,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 55,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 8,
        bookingItemNo: "44606",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>The arch-criminal Matador has devised an evil plan to take over the city. You must use your superhero powers to help save the day!</p>",
        pageTitle: "SUPERHERO'S ADVENTURE ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 8,
            attributes: {
              activityName: "Superhero's Adventure",
              createdAt: "2024-05-17T20:21:11.084Z",
              updatedAt: "2025-07-03T13:40:02.727Z",
              publishedAt: "2024-05-17T20:37:50.709Z",
              activitySlug: "superheros-adventure",
              isPublish: true,
              priority: 6,
              activityInfo: {
                id: 8,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 67,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 9,
        bookingItemNo: "44601",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>As a magician, you have always looked up to Houdini and his impressive skills. Prove you have what it takes to be a Master Magician!</p>",
        pageTitle: "HOUDINI'S PRESTIGE ESCAPE ROOM ",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 7,
            attributes: {
              activityName: "Houdini's Prestige",
              createdAt: "2024-05-17T19:51:17.652Z",
              updatedAt: "2025-07-03T13:41:07.607Z",
              publishedAt: "2024-05-17T20:07:24.112Z",
              activitySlug: "houdinis-prestige",
              isPublish: true,
              priority: 7,
              activityInfo: {
                id: 7,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 42,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 10,
        bookingItemNo: "44602",
        isActive: true,
        teamSize: "2-10",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          "<p>An international jewel thief is about to slip free. Can your team find the clues to stop them from escaping before it is too late?</p>",
        pageTitle: "SPECIAL AGENT ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 6,
            attributes: {
              activityName: "Special Agent",
              createdAt: "2024-05-17T19:30:15.023Z",
              updatedAt: "2026-01-19T12:19:34.829Z",
              publishedAt: "2024-05-17T19:49:02.290Z",
              activitySlug: "special-agent",
              isPublish: true,
              priority: 8,
              activityInfo: {
                id: 6,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 65,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
      {
        id: 11,
        bookingItemNo: "44605",
        isActive: true,
        teamSize: "2-6",
        teamSizeLabel: "Team Size",
        pageSubTitle:
          '<p>Find the lost director\'s cut of "Adventure Hour" within the next hour to declare your movie theater a historic landmark and save it from demolition.</p>',
        pageTitle: "REEL OF FORTUNE ESCAPE ROOM",
        pageNotice: null,
        storyLineLabel: null,
        storyLineText: null,
        plotLabel: null,
        plotText: null,
        missionLabel: null,
        missionText: null,
        activity: {
          data: {
            id: 17,
            attributes: {
              activityName: "Reel of Fortune",
              createdAt: "2024-05-14T20:13:23.088Z",
              updatedAt: "2025-07-03T13:43:28.638Z",
              publishedAt: "2025-04-16T06:46:34.290Z",
              activitySlug: "reel-of-fortune",
              isPublish: true,
              priority: 9,
              activityInfo: {
                id: 17,
                category: "Escape Games",
                duration: 60,
                age: "6+",
                successRate: 64,
                teamSizeLabel: "Team Size",
                privateEvents: "YES",
                teamSize: "2-10",
              },
            },
          },
        },
      },
    ],
    escapeGameParty: [
      {
        id: 11,
        partyName: "Escape From Alcatraz",
        teamSize: null,
        teamSizeLabel: null,
        duration: null,
        sliderText: null,
        bookingItemNo: 579667,
        bookingFlow: "17838",
        isActive: true,
        ageRange: null,
        priority: null,
        partyCardText:
          "<p>Our Party Package offers an exciting Escape From Alcatraz escape room experience for up to 10 guests for one hour plus a two-hour rental of the party room. We'll provide basic supplies like plates, napkins, and utensils. Plus, you'll receive free digital All In Adventures birthday invitations that you can print.</p>",
        bookingButtonText: "BOOK NOW",
        isActiveList: false,
        linkedActivity: { data: null },
        activityListImage: { data: null },
      },
      {
        id: 12,
        partyName: "Zombie Apocalypse",
        teamSize: null,
        teamSizeLabel: null,
        duration: null,
        sliderText: null,
        bookingItemNo: 579669,
        bookingFlow: "17838",
        isActive: null,
        ageRange: null,
        priority: null,
        partyCardText:
          "<p>Our Party Package offers an exciting Zombie Apocalypse escape room experience for up to 10 guests for one hour plus a two-hour rental of the party room. We'll provide basic supplies like plates, napkins, and utensils. Plus, you'll receive free digital All In Adventures birthday invitations that you can print.</p>",
        bookingButtonText: "BOOK NOW",
        isActiveList: false,
        linkedActivity: { data: null },
        activityListImage: { data: null },
      },
      {
        id: 13,
        partyName: "Treasure Island",
        teamSize: null,
        teamSizeLabel: null,
        duration: null,
        sliderText: null,
        bookingItemNo: 579668,
        bookingFlow: "17838",
        isActive: null,
        ageRange: null,
        priority: null,
        partyCardText:
          "<p>Our Party Package offers an exciting Treasure Island escape room experience for up to 10 guests for one hour plus a two-hour rental of the party room. We'll provide basic supplies like plates, napkins, and utensils. Plus, you'll receive free digital All In Adventures birthday invitations that you can print.</p>",
        bookingButtonText: "BOOK NOW",
        isActiveList: false,
        linkedActivity: { data: null },
        activityListImage: { data: null },
      },
    ],
  },
};
