export const getAllActivity=()=>{

    const allActivityList={

       
            "pagemeta":{

                "matatilte":"title",
                "metakeyword":"keywords",
                "metadescription":"metadescription"
              },
               
              "pagedata": {
                           "pagetitle":"ALL ESCAPE ROOM AND ACTIVITIES",
                           "pagesubtitle":"#1 Place for fun adventure activities and events with escape games, axe throwing, virtual reality, game show room, beat the seat. Bring your friend & family today. ",
                            "totalLocations": "28",
                            "totalUniqueGames": "11",
                           "totalFiveStarReview": "60k+",
                          "totalPlayerEscaped": "90k+",
                            "coverimageL":"/assets/location-hero-bg.jpg",
                            "coverimageM":"/assets/location-hero.jpg"
              },

              "activity_list":[

                {
                    "id":1,
                    "activity_name":"Escape from Alcatraz",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":10,
                    "price":30,
                    "duration":50,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"escape-from-alcatraz",
                    "activity_cover_image":"/assets/game-list-cover-img-1.jpg",
                    
                },
                {
                    "id":2,
                    "activity_name":"Treasure Island",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":36,
                    "duration":50,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"treasure-island",
                    "activity_cover_image":"/assets/game-list-cover-img.jpg",
                },
                {
                    "id":3,
                    "activity_name":"HOLLYWOOD PREMIERE",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":36,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"hollywood-premiere",
                    "activity_cover_image":"/assets/game-list-cover-img-3.jpg",
                },
                {
                    "id":4,
                    "activity_name":"Lost in The Jungle",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"lost-in-the-jungle",
                    "activity_cover_image":"/assets/game-list-cover-img-2.jpg",
                },
                {
                    "id":5,
                    "activity_name":"Black Ops",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"black-ops",
                    "activity_cover_image":"/assets/game-list-cover-img-4.jpg",
                },
                {
                    "id":6,
                    "activity_name":"Locked in the Lift",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"locked-in-the-Lift",
                    "activity_cover_image":"/assets/game-list-cover-img-5.jpg",
                },
                {
                    "id":7,
                    "activity_name":"HOUDINI'S MAGIC CELL",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"houdinis-magic-cell",
                    "activity_cover_image":"/assets/game-list-cover-img-6.jpg",
                },
                {
                    "id":8,
                    "activity_name":"MAGIC CASTLE",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"magic-castle",
                    "activity_cover_image":"/assets/game-list-cover-img-7.jpg",
                },
                {
                    "id":9,
                    "activity_name":"Superhero's Adventure",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"superheros-adventure",
                    "activity_cover_image":"/assets/game-list-cover-img-2.jpg",
                },
                {
                    "id":10,
                    "activity_name":"Zombie Apocalypse",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"zombie-apocalypse",
                    "activity_cover_image":"/assets/game-list-cover-img-4.jpg",
                },
                {
                    "id":11,
                    "activity_name":"Special Agent",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"special-agent",
                    "activity_cover_image":"/assets/game-list-cover-img-6.jpg",
                },
                {
                    "id":12,
                    "activity_name":"Sherlock's Library",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"sherlocks-library",
                    "activity_cover_image":"/assets/game-list-cover-img-5.jpg",
                },
                {
                    "id":13,
                    "activity_name":"Wizarding School ",
                    "activity_type":"In person",
                    "activity_category":"escapegame",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"wizarding-school ",
                    "activity_cover_image":"/assets/game-list-cover-img-3.jpg",
                },
                {
                    "id":14,
                    "activity_name":"Beat The Seat",
                    "activity_type":"In person",
                    "activity_category":"other",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"beat-the-seat",
                    "activity_cover_image":"/assets/game-list-cover-img-1.jpg",
                },
                {
                    "id":15,
                    "activity_name":"Game Show Room",
                    "activity_type":"In person",
                    "activity_category":"other",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"game-show-room",
                    "activity_cover_image":"/assets/game-list-cover-img-2.jpg",
                },
                {
                    "id":16,
                    "activity_name":"Axe Throwing",
                    "activity_type":"In person",
                    "activity_category":"other",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"axe-throwing",
                    "activity_cover_image":"/assets/game-list-cover-img-3.jpg",
                },
                {
                    "id":17,
                    "activity_name":"Virtual Reality",
                    "activity_type":"In person",
                    "activity_category":"other",
                    "age":"all Aage",
                    "min_player":2,
                    "max_player":8,
                    "price":28,
                    "duration":60,
                    "activity_desc":"Select the number of participants fill out the details. fill out the number of details.",
                    "activity_slug":"virtual-reality",
                    "activity_cover_image":"/assets/game-list-cover-img-5.jpg",
                },
                
                
                

              ]
        
    }

    return allActivityList

}