const locations = [
  {
    id: 2,
    locationSlug: "albany-ny",
    locationName: "Albany, NY",
    locationActivities: [
      {
        id: 1,
        bookingItemNo: "44609",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 2,
        bookingItemNo: "44603",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 5,
        bookingItemNo: "44608",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 6,
        bookingItemNo: "44607",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 7,
        bookingItemNo: "44604",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 8,
        bookingItemNo: "44606",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 9,
        bookingItemNo: "44601",
        isActive: true,
        activityName: "Houdini's Prestige",
        activitySlug: "houdinis-prestige",
      },
      {
        id: 10,
        bookingItemNo: "44602",
        isActive: true,
        activityName: "Special Agent",
        activitySlug: "special-agent",
      },
      {
        id: 11,
        bookingItemNo: "44605",
        isActive: true,
        activityName: "Reel of Fortune",
        activitySlug: "reel-of-fortune",
      },
    ],
  },
  {
    id: 4,
    locationSlug: "middletown-ny",
    locationName: "Middletown, NY",
    locationActivities: [
      {
        id: 16,
        bookingItemNo: "44759",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 19,
        bookingItemNo: "44761",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 18,
        bookingItemNo: "44762",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 13,
        bookingItemNo: "44758",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 17,
        bookingItemNo: "44765",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 15,
        bookingItemNo: "44763",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 14,
        bookingItemNo: "44764",
        isActive: true,
        activityName: "Houdini's Prestige",
        activitySlug: "houdinis-prestige",
      },
      {
        id: 20,
        bookingItemNo: "44766",
        isActive: true,
        activityName: "Special Agent",
        activitySlug: "special-agent",
      },
      {
        id: 12,
        bookingItemNo: "44760",
        isActive: true,
        activityName: "Reel of Fortune",
        activitySlug: "reel-of-fortune",
      },
      {
        id: 21,
        bookingItemNo: "332492",
        isActive: true,
        activityName: "Wizarding School",
        activitySlug: "wizarding-school",
      },
      {
        id: 22,
        bookingItemNo: "325647",
        isActive: true,
        activityName: "Beat The Seat",
        activitySlug: "beat-the-seat",
      },
    ],
  },
  {
    id: 5,
    locationSlug: "syracuse-ny",
    locationName: "Syracuse, NY",
    locationActivities: [
      {
        id: 23,
        bookingItemNo: "44853",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 24,
        bookingItemNo: "44852",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 25,
        bookingItemNo: "44859",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 27,
        bookingItemNo: "44855",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 28,
        bookingItemNo: "44851",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 30,
        bookingItemNo: "44854",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 26,
        bookingItemNo: "44860",
        isActive: true,
        activityName: "Houdini's Prestige",
        activitySlug: "houdinis-prestige",
      },
      {
        id: 31,
        bookingItemNo: "44857",
        isActive: true,
        activityName: "Special Agent",
        activitySlug: "special-agent",
      },
      {
        id: 32,
        bookingItemNo: "44856",
        isActive: true,
        activityName: "Reel of Fortune",
        activitySlug: "reel-of-fortune",
      },
      {
        id: 33,
        bookingItemNo: "318399",
        isActive: true,
        activityName: "Beat The Seat",
        activitySlug: "beat-the-seat",
      },
    ],
  },
  {
    id: 9,
    locationSlug: "watertown-ny",
    locationName: "Watertown, NY",
    locationActivities: [
      {
        id: 70,
        bookingItemNo: "44796",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 69,
        bookingItemNo: "44794",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 65,
        bookingItemNo: "44791",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 66,
        bookingItemNo: "44793",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 72,
        bookingItemNo: "44795",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 67,
        bookingItemNo: "44788",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 73,
        bookingItemNo: "44792",
        isActive: true,
        activityName: "Houdini's Prestige",
        activitySlug: "houdinis-prestige",
      },
      {
        id: 74,
        bookingItemNo: "44797",
        isActive: true,
        activityName: "Special Agent",
        activitySlug: "special-agent",
      },
      {
        id: 71,
        bookingItemNo: "44789",
        isActive: true,
        activityName: "Reel of Fortune",
        activitySlug: "reel-of-fortune",
      },
    ],
  },
  {
    id: 10,
    locationSlug: "west-nyack-ny",
    locationName: "West Nyack, NY",
    locationActivities: [
      {
        id: 82,
        bookingItemNo: "44539",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 75,
        bookingItemNo: "44544",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 83,
        bookingItemNo: "44540",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 84,
        bookingItemNo: "44542",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 76,
        bookingItemNo: "44537",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 256,
        bookingItemNo: "290998",
        isActive: true,
        activityName: "Beat The Seat",
        activitySlug: "beat-the-seat",
      },
      {
        id: 257,
        bookingItemNo: "277259",
        isActive: true,
        activityName: "Game Show Room",
        activitySlug: "game-show-room",
      },
    ],
  },
  {
    id: 8,
    locationSlug: "poughkeepsie-ny",
    locationName: "Poughkeepsie, NY",
    locationActivities: [
      {
        id: 54,
        bookingItemNo: "224037",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 55,
        bookingItemNo: "224032",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 56,
        bookingItemNo: "224071",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 63,
        bookingItemNo: "224063",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 57,
        bookingItemNo: "224006",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 62,
        bookingItemNo: "224038",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
      {
        id: 58,
        bookingItemNo: "224057",
        isActive: true,
        activityName: "Houdini's Prestige",
        activitySlug: "houdinis-prestige",
      },
    ],
  },
  {
    id: 11,
    locationSlug: "raleigh-nc",
    locationName: "Raleigh, NC",
    locationActivities: [
      {
        id: 85,
        bookingItemNo: "53870",
        isActive: true,
        activityName: "Escape From Alcatraz",
        activitySlug: "escape-from-alcatraz",
      },
      {
        id: 86,
        bookingItemNo: "53868",
        isActive: true,
        activityName: "Treasure Island",
        activitySlug: "treasure-island",
      },
      {
        id: 87,
        bookingItemNo: "53892",
        isActive: true,
        activityName: "Zombie Apocalypse",
        activitySlug: "zombie-apocalypse",
      },
      {
        id: 88,
        bookingItemNo: "53879",
        isActive: true,
        activityName: "Sherlock's Library",
        activitySlug: "sherlocks-library",
      },
      {
        id: 258,
        bookingItemNo: "53865",
        isActive: true,
        activityName: "Black Ops",
        activitySlug: "black-ops",
      },
      {
        id: 90,
        bookingItemNo: "53873",
        isActive: true,
        activityName: "Superhero's Adventure",
        activitySlug: "superheros-adventure",
      },
    ],
  },
]
const stateList=[
  {
    id: 1,
    stateName: "New York",
    stateCode: "NY",
    locations: [
      {
        id: 2,
        locationSlug: "albany-ny",
        locationName: "Albany, NY",
        bookingInfo: {
          shortName: "mysteryroom-albany",
          flow: 17838,
        },
        locationActivities: [
          {
            id: 1,
            bookingItemNo: "44609",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 2,
            bookingItemNo: "44603",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 5,
            bookingItemNo: "44608",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 6,
            bookingItemNo: "44607",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 7,
            bookingItemNo: "44604",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 8,
            bookingItemNo: "44606",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 9,
            bookingItemNo: "44601",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 10,
            bookingItemNo: "44602",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 11,
            bookingItemNo: "44605",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 4,
        locationSlug: "middletown-ny",
        locationName: "Middletown, NY",
        bookingInfo: {
          id: 3,
          shortName: "mysteryroom-middletown",
          flow: 17844,
        },
        locationActivities: [
          {
            id: 16,
            bookingItemNo: "44759",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 19,
            bookingItemNo: "44761",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 18,
            bookingItemNo: "44762",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 13,
            bookingItemNo: "44758",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 17,
            bookingItemNo: "44765",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 15,
            bookingItemNo: "44763",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 14,
            bookingItemNo: "44764",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 20,
            bookingItemNo: "44766",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 12,
            bookingItemNo: "44760",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 21,
            bookingItemNo: "332492",
            isActive: true,
            activityName: "Wizarding School",
            activitySlug: "wizarding-school",
          },
          {
            id: 22,
            bookingItemNo: "325647",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
        ],
      },
      {
        id: 5,
        locationSlug: "syracuse-ny",
        locationName: "Syracuse, NY",
        bookingInfo: {
          id: 4,
          shortName: "mysteryroom-syracuse",
          flow: 17847,

        },
        locationActivities: [
          {
            id: 23,
            bookingItemNo: "44853",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 24,
            bookingItemNo: "44852",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 25,
            bookingItemNo: "44859",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 27,
            bookingItemNo: "44855",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 28,
            bookingItemNo: "44851",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 30,
            bookingItemNo: "44854",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 26,
            bookingItemNo: "44860",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 31,
            bookingItemNo: "44857",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 32,
            bookingItemNo: "44856",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 33,
            bookingItemNo: "318399",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
        ],
      },
      {
        id: 9,
        locationSlug: "watertown-ny",
        locationName: "Watertown, NY",
        bookingInfo: {
          id: 8,
          shortName: "mysteryroom-watertown",
          flow: 17848,
        },
        locationActivities: [
          {
            id: 70,
            bookingItemNo: "44796",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 69,
            bookingItemNo: "44794",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 65,
            bookingItemNo: "44791",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 66,
            bookingItemNo: "44793",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 72,
            bookingItemNo: "44795",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 67,
            bookingItemNo: "44788",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 73,
            bookingItemNo: "44792",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 74,
            bookingItemNo: "44797",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 71,
            bookingItemNo: "44789",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 10,
        locationSlug: "west-nyack-ny",
        locationName: "West Nyack, NY",
        bookingInfo: {
          id: 9,
          shortName: "mysteryroom-westnyack",
          flow: 17849,
        },
        locationActivities: [
          {
            id: 82,
            bookingItemNo: "44539",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 75,
            bookingItemNo: "44544",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 83,
            bookingItemNo: "44540",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 84,
            bookingItemNo: "44542",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 76,
            bookingItemNo: "44537",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 256,
            bookingItemNo: "290998",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
          {
            id: 257,
            bookingItemNo: "277259",
            isActive: true,
            activityName: "Game Show Room",
            activitySlug: "game-show-room",
          },
        ],
      }
    ],
  },
  {
    id: 2,
    stateName: "North Carolina",
    stateCode: "NC",
    locations: [
      {
        id: 11,
        locationSlug: "raleigh-nc",
        locationName: "Raleigh, NC",
        bookingInfo: {
          id: 10,
          shortName: "allinadventures-raleigh",
          flow: 16807,
        },
        locationActivities: [
          {
            id: 85,
            bookingItemNo: "53870",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 86,
            bookingItemNo: "53868",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 87,
            bookingItemNo: "53892",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 88,
            bookingItemNo: "53879",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 258,
            bookingItemNo: "53865",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 90,
            bookingItemNo: "53873",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    stateName: "Massachusetts",
    stateCode: "MA",
    locations: [
      {
        id: 12,
        locationSlug: "hadley-ma",
        locationName: "Hadley, MA",
        bookingInfo: {
          id: 11,
          shortName: "allinadventures-hadley",
          flow: 15424,
        },
        locationActivities: [
          {
            id: 95,
            bookingItemNo: "49949",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 96,
            bookingItemNo: "49947",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 97,
            bookingItemNo: "49964",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 98,
            bookingItemNo: "49959",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 103,
            bookingItemNo: "49937",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 102,
            bookingItemNo: "49952",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 99,
            bookingItemNo: "49954",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 100,
            bookingItemNo: "49962",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 101,
            bookingItemNo: "49960",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 13,
        locationSlug: "holyoke-ma",
        locationName: "Holyoke, MA",
        bookingInfo: {
          id: 12,
          shortName: "allinadventures-holyoke",
          flow: 15419,
        },
        locationActivities: [
          {
            id: 105,
            bookingItemNo: "51210",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 109,
            bookingItemNo: "51203",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 106,
            bookingItemNo: "51218",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 110,
            bookingItemNo: "53492",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 112,
            bookingItemNo: "51211",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 113,
            bookingItemNo: "51215",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 108,
            bookingItemNo: "51221",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 14,
        locationSlug: "kingston-ma",
        locationName: "Kingston, MA",
        bookingInfo: {
          id: 13,
          shortName: "mysteryroom-kingston",
          flow: 17841,
        },
        locationActivities: [
          {
            id: 123,
            bookingItemNo: "44587",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 115,
            bookingItemNo: "44588",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 118,
            bookingItemNo: "44581",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 119,
            bookingItemNo: "44584",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 120,
            bookingItemNo: "44585",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 121,
            bookingItemNo: "44589",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 116,
            bookingItemNo: "44586",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 124,
            bookingItemNo: "44582",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 255,
            bookingItemNo: "332716",
            isActive: true,
            activityName: "Lost in The Jungle",
            activitySlug: "lost-in-the-jungle",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    stateName: "Connecticut",
    stateCode: "CT",
    locations: [
      {
        id: 16,
        locationSlug: "milford-ct",
        locationName: "Milford, CT",
        bookingInfo: {
          id: 15,
          shortName: "mysteryroom-milford",
          flow: 2018,
        },
        locationActivities: [
          {
            id: 139,
            bookingItemNo: "44820",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 144,
            bookingItemNo: "44827",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 140,
            bookingItemNo: "44828",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 135,
            bookingItemNo: "44825",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 136,
            bookingItemNo: "44829",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 141,
            bookingItemNo: "44821",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 142,
            bookingItemNo: "44823",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 17,
        locationSlug: "manchester-ct",
        locationName: "Manchester, CT",
        bookingInfo: {
          id: 16,
          shortName: "allinadventures-manchester",
          flow: 1750,
        },
        locationActivities: [
          {
            id: 151,
            bookingItemNo: "54562",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 152,
            bookingItemNo: "54561",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 145,
            bookingItemNo: "54570",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 154,
            bookingItemNo: "54565",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 146,
            bookingItemNo: "54560",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 153,
            bookingItemNo: "54563",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 147,
            bookingItemNo: "54564",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 148,
            bookingItemNo: "54568",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 149,
            bookingItemNo: "54566",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 9,
    stateName: "Ohio",
    stateCode: "OH",
    locations: [
      {
        id: 27,
        locationSlug: "columbus-oh",
        locationName: "Columbus, OH",
        bookingInfo: {
          id: 26,
          shortName: "allinadventures-columbus-oh",
          flow: 17847,
        },
        locationActivities: [
          {
            id: 249,
            bookingItemNo: "55169",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 254,
            bookingItemNo: "55168",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 251,
            bookingItemNo: "530130",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 253,
            bookingItemNo: "55172",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 250,
            bookingItemNo: "603383",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
        ],
      },
    ],
  }
]

const currentAct=[
  {
    id: 1,
    stateName: "New York",
    stateCode: "NY",
    locations: [
      {
        id: 2,
        locationSlug: "albany-ny",
        locationName: "Albany, NY",
        storeEmail: "store103@allinadventures.com",
        managerEmail: "mgr103@allinadventures.com",
        mall: "Crossgates Mall",
        fivestarId: "4fc2ae1b62734a6e8d9e85cbd613ca0f",
        bookingInfo: {
          id: 1,
          shortName: "mysteryroom-albany",
          flow: 17838,
          partyPackageItemNo: 44613,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360203,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: 571322,
          playPassFlow: "no",
        },
        locationActivities: [
          {
            id: 1,
            bookingItemNo: "44609",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 2,
            bookingItemNo: "44603",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 5,
            bookingItemNo: "44608",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 6,
            bookingItemNo: "44607",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 7,
            bookingItemNo: "44604",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 8,
            bookingItemNo: "44606",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 9,
            bookingItemNo: "44601",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 10,
            bookingItemNo: "44602",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 11,
            bookingItemNo: "44605",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 4,
        locationSlug: "middletown-ny",
        locationName: "Middletown, NY",
        storeEmail: "store105@allinadventures.com",
        managerEmail: "mgr105@allinadventures.com",
        mall: "Galleria at Crystal Run",
        fivestarId: "c78436588d1e4a02a7b15efc3a428a18",
        bookingInfo: {
          id: 3,
          shortName: "mysteryroom-middletown",
          flow: 17844,
          partyPackageItemNo: 44769,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360208,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 16,
            bookingItemNo: "44759",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 19,
            bookingItemNo: "44761",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 18,
            bookingItemNo: "44762",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 13,
            bookingItemNo: "44758",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 17,
            bookingItemNo: "44765",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 15,
            bookingItemNo: "44763",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 14,
            bookingItemNo: "44764",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 20,
            bookingItemNo: "44766",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 12,
            bookingItemNo: "44760",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 21,
            bookingItemNo: "332492",
            isActive: true,
            activityName: "Wizarding School",
            activitySlug: "wizarding-school",
          },
          {
            id: 22,
            bookingItemNo: "325647",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
        ],
      },
      {
        id: 5,
        locationSlug: "syracuse-ny",
        locationName: "Syracuse, NY",
        storeEmail: "store107@allinadventures.com",
        managerEmail: "mgr107@allinadventures.com",
        mall: "Destiny USA",
        fivestarId: "57c2d1d5139042a8993b262968364733",
        bookingInfo: {
          id: 4,
          shortName: "mysteryroom-syracuse",
          flow: 17847,
          partyPackageItemNo: 44861,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360211,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 23,
            bookingItemNo: "44853",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 24,
            bookingItemNo: "44852",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 25,
            bookingItemNo: "44859",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 27,
            bookingItemNo: "44855",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 28,
            bookingItemNo: "44851",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 30,
            bookingItemNo: "44854",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 26,
            bookingItemNo: "44860",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 31,
            bookingItemNo: "44857",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 32,
            bookingItemNo: "44856",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 33,
            bookingItemNo: "318399",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
        ],
      },
      {
        id: 9,
        locationSlug: "watertown-ny",
        locationName: "Watertown, NY",
        storeEmail: "store106@allinadventures.com",
        managerEmail: "mgr10@allinadventures.com",
        mall: "Salmon Run Mall",
        fivestarId: "6fb541ac4d0445608e5169c95c142791",
        bookingInfo: {
          id: 8,
          shortName: "mysteryroom-watertown",
          flow: 17848,
          partyPackageItemNo: 44799,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360212,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 70,
            bookingItemNo: "44796",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 69,
            bookingItemNo: "44794",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 65,
            bookingItemNo: "44791",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 66,
            bookingItemNo: "44793",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 72,
            bookingItemNo: "44795",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 67,
            bookingItemNo: "44788",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 73,
            bookingItemNo: "44792",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 74,
            bookingItemNo: "44797",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 71,
            bookingItemNo: "44789",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 10,
        locationSlug: "west-nyack-ny",
        locationName: "West Nyack, NY",
        storeEmail: "store101@allinadventures.com",
        managerEmail: "mgr101@allinadventures.com",
        mall: "Palisades Center",
        fivestarId: "08695bcfdbd0498d8cd25a03361cf80d",
        bookingInfo: {
          id: 9,
          shortName: "mysteryroom-westnyack",
          flow: 17849,
          partyPackageItemNo: 44555,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360213,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 82,
            bookingItemNo: "44539",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 75,
            bookingItemNo: "44544",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 83,
            bookingItemNo: "44540",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 84,
            bookingItemNo: "44542",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 76,
            bookingItemNo: "44537",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 256,
            bookingItemNo: "290998",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
          {
            id: 257,
            bookingItemNo: "277259",
            isActive: true,
            activityName: "Game Show Room",
            activitySlug: "game-show-room",
          },
        ],
      },
      {
        id: 8,
        locationSlug: "poughkeepsie-ny",
        locationName: "Poughkeepsie, NY",
        storeEmail: "store149@allinadventures.com",
        managerEmail: "mgr149@allinadventures.com",
        mall: "Poughkeepsie Galleria",
        fivestarId: "4839a23169024bc8932f64b6d1f2c504",
        bookingInfo: {
          id: 7,
          shortName: "allinadventures-poughkeepsie",
          flow: 365583,
          partyPackageItemNo: 426690,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360256,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 54,
            bookingItemNo: "224037",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 55,
            bookingItemNo: "224032",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 56,
            bookingItemNo: "224071",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 63,
            bookingItemNo: "224063",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 57,
            bookingItemNo: "224006",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 62,
            bookingItemNo: "224038",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 58,
            bookingItemNo: "224057",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    stateName: "North Carolina",
    stateCode: "NC",
    locations: [
      {
        id: 11,
        locationSlug: "raleigh-nc",
        locationName: "Raleigh, NC",
        storeEmail: "store123@allinadventures.com",
        managerEmail: "mgr123@allinadventures.com",
        mall: "Triangle Town Center",
        fivestarId: "32cdb7144e66428bbc9af9393a94d362",
        bookingInfo: {
          id: 10,
          shortName: "allinadventures-raleigh",
          flow: 16807,
          partyPackageItemNo: 53895,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360258,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 85,
            bookingItemNo: "53870",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 86,
            bookingItemNo: "53868",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 87,
            bookingItemNo: "53892",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 88,
            bookingItemNo: "53879",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 258,
            bookingItemNo: "53865",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 90,
            bookingItemNo: "53873",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    stateName: "Massachusetts",
    stateCode: "MA",
    locations: [
      {
        id: 12,
        locationSlug: "hadley-ma",
        locationName: "Hadley, MA",
        storeEmail: "store113@allinadventures.com",
        managerEmail: "mgr113@allinadventures.com",
        mall: "Hampshire Mall",
        fivestarId: "fd585cfcb0ae4d7f8179dd084d3c7f14",
        bookingInfo: {
          id: 11,
          shortName: "allinadventures-hadley",
          flow: 15424,
          partyPackageItemNo: 50101,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360214,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 95,
            bookingItemNo: "49949",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 96,
            bookingItemNo: "49947",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 97,
            bookingItemNo: "49964",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 98,
            bookingItemNo: "49959",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 103,
            bookingItemNo: "49937",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 102,
            bookingItemNo: "49952",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 99,
            bookingItemNo: "49954",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 100,
            bookingItemNo: "49962",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 101,
            bookingItemNo: "49960",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 13,
        locationSlug: "holyoke-ma",
        locationName: "Holyoke, MA",
        storeEmail: "store114@allinadventures.com",
        managerEmail: "mgr114@allinadventures.com",
        mall: "Holyoke Mall",
        fivestarId: "0c3dbc2e3a7340ba9f598fd150cc38f8",
        bookingInfo: {
          id: 12,
          shortName: "allinadventures-holyoke",
          flow: 15419,
          partyPackageItemNo: 51224,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360215,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 105,
            bookingItemNo: "51210",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 109,
            bookingItemNo: "51203",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 106,
            bookingItemNo: "51218",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 110,
            bookingItemNo: "53492",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 112,
            bookingItemNo: "51211",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 113,
            bookingItemNo: "51215",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 108,
            bookingItemNo: "51221",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 14,
        locationSlug: "kingston-ma",
        locationName: "Kingston, MA",
        storeEmail: "store102@allinadventures.com",
        managerEmail: "mgr102@allinadventures.com",
        mall: "Kingston Collection",
        fivestarId: "18babca8503848fea92d33ed8f45fa83",
        bookingInfo: {
          id: 13,
          shortName: "mysteryroom-kingston",
          flow: 17841,
          partyPackageItemNo: 44592,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360207,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 123,
            bookingItemNo: "44587",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 115,
            bookingItemNo: "44588",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 118,
            bookingItemNo: "44581",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 119,
            bookingItemNo: "44584",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 120,
            bookingItemNo: "44585",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 121,
            bookingItemNo: "44589",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 116,
            bookingItemNo: "44586",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 124,
            bookingItemNo: "44582",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 255,
            bookingItemNo: "332716",
            isActive: true,
            activityName: "Lost in The Jungle",
            activitySlug: "lost-in-the-jungle",
          },
        ],
      },
      {
        id: 15,
        locationSlug: "n-attleborough-ma",
        locationName: "N. Attleborough, MA",
        storeEmail: "store110@allinadventures.com",
        managerEmail: "mgr110@allinadventures.com",
        mall: "Emerald Square Mall",
        fivestarId: "8b631dac8b8e4614b1479de58de8fd00",
        bookingInfo: {
          id: 14,
          shortName: "mysteryroom-attleboro",
          flow: 17846,
          partyPackageItemNo: 48113,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360205,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 125,
            bookingItemNo: "44779",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 126,
            bookingItemNo: "44785",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 127,
            bookingItemNo: "44786",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 134,
            bookingItemNo: "44783",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 133,
            bookingItemNo: "44787",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 132,
            bookingItemNo: "44780",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 128,
            bookingItemNo: "44784",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 129,
            bookingItemNo: "44782",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 130,
            bookingItemNo: "44781",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    stateName: "Connecticut",
    stateCode: "CT",
    locations: [
      {
        id: 16,
        locationSlug: "milford-ct",
        locationName: "Milford, CT",
        storeEmail: "store109@allinadventures.com",
        managerEmail: "mgr109@allinadventures.com",
        mall: "Connecticut Post Mall",
        fivestarId: "084e7f2381b04d689960cc4161935ed7",
        bookingInfo: {
          id: 15,
          shortName: "mysteryroom-milford",
          flow: 2018,
          partyPackageItemNo: 44849,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360209,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 139,
            bookingItemNo: "44820",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 144,
            bookingItemNo: "44827",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 140,
            bookingItemNo: "44828",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 135,
            bookingItemNo: "44825",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 136,
            bookingItemNo: "44829",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 141,
            bookingItemNo: "44821",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 142,
            bookingItemNo: "44823",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
      {
        id: 17,
        locationSlug: "manchester-ct",
        locationName: "Manchester, CT",
        storeEmail: "store121@allinadventures.com",
        managerEmail: "mgr121@allinadventures.com",
        mall: "The Shoppes at Buckland Hills",
        fivestarId: "d9626bc988b940768ee6bd60acda7340",
        bookingInfo: {
          id: 16,
          shortName: "allinadventures-manchester",
          flow: 1750,
          partyPackageItemNo: 54571,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360244,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 151,
            bookingItemNo: "54562",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 152,
            bookingItemNo: "54561",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 145,
            bookingItemNo: "54570",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 154,
            bookingItemNo: "54565",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 146,
            bookingItemNo: "54560",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 153,
            bookingItemNo: "54563",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 147,
            bookingItemNo: "54564",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 148,
            bookingItemNo: "54568",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 149,
            bookingItemNo: "54566",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    stateName: "Maryland",
    stateCode: "MD",
    locations: [
      {
        id: 20,
        locationSlug: "bowie-md",
        locationName: "Bowie, MD",
        storeEmail: "store145@allinadventures.com",
        managerEmail: "mgr145@allinadventures.com",
        mall: "Bowie Town Center",
        fivestarId: "c291a32e29f54d8dbafe05d862bc3f2c",
        bookingInfo: {
          id: 19,
          shortName: "allinadventures-bowie",
          flow: 17839,
          partyPackageItemNo: 104527,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360250,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 175,
            bookingItemNo: "104494",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 179,
            bookingItemNo: "104493",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 177,
            bookingItemNo: "104500",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 180,
            bookingItemNo: "104497",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 184,
            bookingItemNo: "104491",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 181,
            bookingItemNo: "104495",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 178,
            bookingItemNo: "104496",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 261,
            bookingItemNo: "104498",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
        ],
      },
      {
        id: 21,
        locationSlug: "white-marsh-md",
        locationName: "White Marsh, MD",
        storeEmail: "store118@allinadventures.com",
        managerEmail: "mgr118@allinadventures.com",
        mall: "White Marsh Mall",
        fivestarId: "ad62a4bc27bf471e80eb1eb90aba7cc5",
        bookingInfo: {
          id: 20,
          shortName: "allinadventures-whitemarsh",
          flow: 14683,
          partyPackageItemNo: 17839,
          activePartyPackage: false,
          activeGiftCard: true,
          giftCardItemNo: 360217,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 185,
            bookingItemNo: "53750",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 187,
            bookingItemNo: "53747",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 189,
            bookingItemNo: "53772",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 193,
            bookingItemNo: "53760",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 192,
            bookingItemNo: "53743",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 188,
            bookingItemNo: "53755",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 186,
            bookingItemNo: "53756",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 194,
            bookingItemNo: "53766",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 190,
            bookingItemNo: "53763",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    stateName: "New Jersey",
    stateCode: "NJ",
    locations: [
      {
        id: 23,
        locationSlug: "rockaway-nj",
        locationName: "Rockaway, NJ",
        storeEmail: "store112@allinadventures.com",
        managerEmail: "mgr112@allinadventures.com",
        mall: "Rockaway Townsquare",
        fivestarId: "f44827aa62c544f58eb5510b38f95f3c",
        bookingInfo: {
          id: 22,
          shortName: "mysteryroom-rockaway",
          flow: 17098,
          partyPackageItemNo: 47198,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360210,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 210,
            bookingItemNo: "44839",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 212,
            bookingItemNo: "44838",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 209,
            bookingItemNo: "44843",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 211,
            bookingItemNo: "44841",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 205,
            bookingItemNo: "44836",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 206,
            bookingItemNo: "44840",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 207,
            bookingItemNo: "44844",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 208,
            bookingItemNo: "44842",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
          {
            id: 260,
            bookingItemNo: "294163",
            isActive: true,
            activityName: "Game Show Room",
            activitySlug: "game-show-room",
          },
        ],
      },
      {
        id: 24,
        locationSlug: "woodbridge-nj",
        locationName: "Woodbridge, NJ",
        storeEmail: "store128@allinadventures.com",
        managerEmail: "mgr128@allinadventures.com",
        mall: "Woodbridge Center",
        fivestarId: "01211af1da0c4ed3b90b346cfd6db1c8",
        bookingInfo: {
          id: 23,
          shortName: "allinadventures-woodbridge",
          flow: 16814,
          partyPackageItemNo: 55163,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360249,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 218,
            bookingItemNo: "55030",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 220,
            bookingItemNo: "55026",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 224,
            bookingItemNo: "55162",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 221,
            bookingItemNo: "55037",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 222,
            bookingItemNo: "55023",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 223,
            bookingItemNo: "55032",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 215,
            bookingItemNo: "55035",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 217,
            bookingItemNo: "55043",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 216,
            bookingItemNo: "55041",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 7,
    stateName: "Virginia",
    stateCode: "VA",
    locations: [
      {
        id: 25,
        locationSlug: "roanoke-va",
        locationName: "Roanoke, VA",
        storeEmail: "store129@allinadventures.com",
        managerEmail: "mgr129@allinadventures.com",
        mall: "Valley View Mall",
        fivestarId: "80da445abe054678b64f5c03def262f0",
        bookingInfo: {
          id: 24,
          shortName: "allinadventures-roanoke",
          flow: 5835,
          partyPackageItemNo: 54397,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360257,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 225,
            bookingItemNo: "54385",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 226,
            bookingItemNo: "54384",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 232,
            bookingItemNo: "54396",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 229,
            bookingItemNo: "54390",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 228,
            bookingItemNo: "54383",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 234,
            bookingItemNo: "54388",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 230,
            bookingItemNo: "54389",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 231,
            bookingItemNo: "54392",
            isActive: true,
            activityName: "Special Agent",
            activitySlug: "special-agent",
          },
          {
            id: 227,
            bookingItemNo: "54391",
            isActive: true,
            activityName: "Reel of Fortune",
            activitySlug: "reel-of-fortune",
          },
        ],
      },
    ],
  },
  {
    id: 8,
    stateName: "Georgia",
    stateCode: "GA",
    locations: [
      {
        id: 26,
        locationSlug: "lawrenceville-ga",
        locationName: "Lawrenceville, GA",
        storeEmail: "store100@allinadventures.com",
        managerEmail: "mgr100@allinadventures.com",
        mall: "Sugarloaf Mills",
        fivestarId: "5cce16b28a96404d898f5d66372a3acc",
        bookingInfo: {
          id: 25,
          shortName: "mysteryroom-lawrenceville",
          flow: 17843,
          partyPackageItemNo: 44742,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 357804,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 235,
            bookingItemNo: "415147",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 236,
            bookingItemNo: "370146",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 237,
            bookingItemNo: "44727",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 240,
            bookingItemNo: "44728",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 238,
            bookingItemNo: "44724",
            isActive: true,
            activityName: "Black Ops",
            activitySlug: "black-ops",
          },
          {
            id: 241,
            bookingItemNo: "44729",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
          {
            id: 243,
            bookingItemNo: "44730",
            isActive: true,
            activityName: "Houdini's Prestige",
            activitySlug: "houdinis-prestige",
          },
          {
            id: 244,
            bookingItemNo: "315932",
            isActive: true,
            activityName: "Beat The Seat",
            activitySlug: "beat-the-seat",
          },
        ],
      },
    ],
  },
  {
    id: 9,
    stateName: "Ohio",
    stateCode: "OH",
    locations: [
      {
        id: 27,
        locationSlug: "columbus-oh",
        locationName: "Columbus, OH",
        storeEmail: "store147@allinadventures.com",
        managerEmail: "mgr147@allinadventures.com",
        mall: "Polaris Fashion Place",
        fivestarId: "6dae166134cf48e8b54ea03a3801acfe",
        bookingInfo: {
          id: 26,
          shortName: "allinadventures-columbus-oh",
          flow: 17847,
          partyPackageItemNo: 55177,
          activePartyPackage: true,
          activeGiftCard: true,
          giftCardItemNo: 360253,
          giftFlow: "no",
          partyPackageFlow: "no",
          playPassItemNo: null,
          playPassFlow: null,
        },
        locationActivities: [
          {
            id: 249,
            bookingItemNo: "55169",
            isActive: true,
            activityName: "Escape From Alcatraz",
            activitySlug: "escape-from-alcatraz",
          },
          {
            id: 254,
            bookingItemNo: "55168",
            isActive: true,
            activityName: "Treasure Island",
            activitySlug: "treasure-island",
          },
          {
            id: 251,
            bookingItemNo: "530130",
            isActive: true,
            activityName: "Zombie Apocalypse",
            activitySlug: "zombie-apocalypse",
          },
          {
            id: 253,
            bookingItemNo: "55172",
            isActive: true,
            activityName: "Sherlock's Library",
            activitySlug: "sherlocks-library",
          },
          {
            id: 250,
            bookingItemNo: "603383",
            isActive: true,
            activityName: "Superhero's Adventure",
            activitySlug: "superheros-adventure",
          },
        ],
      },
    ],
  }
];
