const format = {
  "erban-dictionary-easy-guide-to-escape-room-jargons": {
    pagemeta: {
      title: "ERban DICTIONARY: EASY GUIDE TO ESCAPE ROOM JARGONS",
      description:
        "Escape rooms have only grown in popularity since their beginning nearly twenty years ago. Over its growth in the past decades, the escape room industry has developed its own phrases and lingos used within the industry. If you want to dive deeper into the escape room industry and speak the escape room language. Getting familiar with the specific escape room vocabulary is highly advised.",
      keywords:
        "escape room guide,escape room dictionary,escape room hints,escape room tutorial,escape room jargons, play an escape room,book escape room, escape room news, all in adventures articles,",
      url: "erban-dictionary-easy-guide-to-escape-room-jargons",
      metaindex: true,
      metaimg:
        "/assets/blogs/hero-erban-dictionary-easy-guide-to-escape-room-jargons.jpg",
    },
    pagedata: {
      pagetitle: "ERban DICTIONARY: EASY GUIDE TO ESCAPE ROOM JARGONS",
      description:
        "Escape rooms have only grown in popularity since their beginning nearly twenty years ago. Over its growth in the past decades, the escape room industry has developed its own phrases and lingos used within the industry. If you want to dive deeper into the escape room industry and speak the escape room language. Getting familiar with the specific escape room vocabulary is highly advised.",
      ftimg:
        "/assets/blogs/hero-erban-dictionary-easy-guide-to-escape-room-jargons.jpg",
    },
    bloginfo: {
      authimg: "/assets/blogs/blog-auth1.png",
      authname: "Brian Capps",
      popular: false,
      blogcategory: [
        {
          id: "1",
          name: "Tips & Tricks",
          slug: "tips-and-tricks",
        },
        {
          id: "2",
          name: "franchise",
          slug: "franchise",
        },
      ],
      createdate: "May 29, 2023",
      lastupdate: "May 29, 2023",
    },
    blogdesc: [
      '<div class="sbl-block">',
      "<p>Escape rooms have only grown in popularity since their beginning nearly twenty years ago. Over its growth in the past decades, the escape room industry has developed its own phrases and lingos used within the industry. If you want to dive deeper into the escape room industry and speak the escape room language. Getting familiar with the specific escape room vocabulary is highly advised.</p>",
      "<p>We&prime;ve compiled a comprehensive glossary of the words, names, and expressions that every escape room employee or fanatic should know. The chronology is in ascending order from A to Z and has been categorized for your facilitation. </p>",
      '<p>At All In Adventures, we have a <a href="/activities">variety of thrilling themes</a>, such as Special Agent, Black Ops, and Zombie Apocalypse, that are perfect for creating an unforgettable team-building experience. Use our private rooms before or after the game, enjoy our catering options, or bring personal snacks. Conveniently located in malls, our escape rooms provide an excellent opportunity for a fun day out with your team while building strong relationships.</p>',
      "<p>Now you can impress anyone in the escape room industry, or maybe you are searching for jobs in the escape room industry. Study this handy glossary, and you can soon be fully fluent in escape room lingo.</p>",

      "</div>",

      '<div class="sbl-block">',
      "<h2>THE MOST COMMONLY USED ESCAPE ROOM TERMS</h2>",
      '<p><img src="/assets/blogs/the-most-commonly-used-escape-room-terms.jpg"/></p>',
      "<p><b>Bypass / Circumvent - (verb):</b> to skip over an element in the game. It can either be intentional or unintentional. It can result from hints, lock exploitation, game design flaws, or faulty game resets.</p>",
      "<p><b>Cipher / Cryptogram</b> - (noun, singular): a text which is written in codes.</p>",
      "<p><b>Clue</b> - (noun, singular): detail within the game that the players should interpret and solve to escape. This term can be confusing as it sometimes refers to a hint.</p>",
      "<p><b>Decor</b> - (noun, singular): furnishing and decorating the escape room that provides ambiance. It is not to be confused with red herrings.</p>",
      "<p><b>Escape Rate of Game</b> - (noun, singular): the rate of success of all players for completing the room successfully. Generally, escape room difficulties are evaluated by this. </p>",
      "<p><b>Escape Rate of the players</b> - (noun, singular): players' personal pass/failure rate that lets you know their average success rate at escape rooms. It indicates how experienced a player is at escape rooms.</p>",
      "<p><b>Escape Time</b> - (noun, singular): how long a group took to escape the room or complete the mission.</p>",
      "<p><b>Exit Game Review</b> - (noun, singular): showing the room to players right after they've finished.</p>",
      '<p><img src="/assets/blogs/game-clock.jpg"/></p>',
      "<p><b>Game Clock</b> - (noun, singular): the official countdown timer. It is frequently displayed within the game.</p>",
      "<p><b>Guessing / Brute Force</b> -(noun, singular): coming up with the last missing bit of information to open a lock or solve a puzzle by chance or at random. </p>",

      "<p><b>Hint</b> - (noun, singular): any additional information from outside gameplay delivered by the gamemaster or automated system to assist a team in progress. This concept can sometimes be called a clue.</p>",
      "<p><b>Immersive</b> - (adjectives): describes an escape room that creates such compelling fiction that players feel they are a part of it and forget their world outside the escape room.</p>",
      "<p><b>Jump Scare</b> - (noun, singular): a technique used in horror escape rooms and films to scare players by surprising them with sudden environmental change.</p>",
      '<p><img src="/assets/blogs/key.jpg"/></p>',
      "<p><b>Key</b> - (noun, singular): a small piece of metal with incisions cut to fit a particular lock that can be turned to open or close the lock.</p>",
      "<p><b>Linear</b> - (adjective): a game flow in which puzzles are chronological: one leads to the next, following each other in a straight line. An overly linear game flow limits the surprise factor, which can be predictable for players. Even when a game isn't linear overall, it might include both linear and non-linear elements.</p>",
      "<p><b>Logic Leap</b> - (noun, singular): a connection between a clue and a puzzle solution.</p>",
      "<p><b>Malfunction or Breakage</b> - (noun, singular): when something doesn't work as intended. It can be a structural, electrical, connection, or unknown issue.</p>",
      "<p><b>Non-linear</b> - (adjective): a game that does not follow a puzzle structure where each puzzle leads to the next. Multiple puzzles can be completed at a time, and different teams may tackle puzzles in different orders.</p>",
      "<p><b>Outside Knowledge</b> - (noun, singular): understanding derived from outside the game set that contributes to puzzle-solving within the escape room. What exactly falls into this category may be up for debate. e.g., Roman numerals (especially huge numbers).</p>",
      '<p><img src="/assets/blogs/physical-force.jpg"/></p>',
      "<p><b>Physical Force</b> - (noun, singular): physical strength used to open things. It is usually in violation of game rules and may result in breakage. Note that some escape rooms may require physical force.</p>",
      "<p><b>Production quality</b> - (noun, singular): the quality of an escape room's production; how immersive, elaborate, creative, technologically advanced, etc.</p>",
      "<p><b>Prop</b> - (noun, singular): an item in the game that can be part of a puzzle or a clue.</p>",
      "<p><b>Puzzle</b> - (noun, singular): anything the team needs to solve to advance through the escape room.</p>",
      "<p><b>Red Herring</b> - (noun, singular): an item in-game or information that does not contribute to a puzzle solution but may lead players to waste time thinking it may be involved in the puzzle-solving process. It can be intentional or unintentional, resulting from wear, breakage, or vandalism.</p>",
      "<p><b>Replayability</b> - (noun, singular): whether a game can be played again by the same group or person.</p>",
      "<p><b>Rescheduling</b> - (verb): moving a game to another date, time, or both.</p>",
      '<p><img src="/assets/blogs/reset.jpg"/></p>',
      "<p><b>Reset</b> - (verb): to revert any escape room to its starting position so a new team can begin. e.g., &quot;I have to reset the room for the next team.&quot;</p>",
      "<p><b>Reset error</b> - (noun, singular): a mistake made while resetting the room.</p>",
      "<p><b>Reset Fail</b> - (noun, singular): a reset that is not done correctly and fails to restore all elements of the escape room to their proper starting positions can have a negative effect on the gameplay.</p>",
      "<p><b>Resting Puzzle Face</b> - (noun, singular): a focused expression while solving puzzles may be mistakenly perceived as dissatisfaction.</p>",
      "<p><b>Rules</b> - (noun, plural): the list of actions allowed and prohibited in the experience. Severely ignoring the rules often leads to the players at fault being removed from the game.</p>",
      "<p><b>Skip (a puzzle)</b> - (verb): when players must forgo a puzzle and move on to the next, usually due to malfunction or poor room design.</p>",
      "<p><b>Spoiler</b> - (noun, singular): a description of an essential part of an escape room; if previously known, it might reduce surprise or suspense for a first-time player.</p>",
      '<p><img src="/assets/blogs/team.jpg"/></p>',
      "<p><b>Team</b> - (noun, singular): the group of people you must play the escape room with, communicate and cooperate. These could be people you know and went with or strangers you were paired with. </p>",
      "<p><b>Theme</b> - (adjective): a concept or pre-existing idea that the game is built around, which is usually a large factor in immersion. Themes could be broad such as medieval or prison, or specific such as South Park or Al Capone.</p>",
      "<p><b>Vandalism</b> - (noun, singular): intentional damage done to a room.</p>",
      "<p><b>Walkthrough</b> - (noun): after completing an escape room game (whether won or lost), a review provided by the gamemaster assesses the puzzles and game progression.</p>",

      "</div>",
      '<div class="sbl-block">',
      "<h2>ESCAPE ROOM TECHNOLOGY</h2>",
      '<p><img src="/assets/blogs/escape-room-technology.jpg"/></p>',
      "<p><b>Countdown Timer</b> - (noun, singular): a timer that shows players the time remaining in the game. It can be incorporated into Kiosks or a separate device on the wall.</p>",
      "<p><b>Directional Lock</b> - (noun, singular): often acknowledged by players as the worst type of combination to find, these open from a specific set of directions (up, down, left, right).</p>",
      "<p><b>First Generation Escape Rooms, &quot;GEN1&quot;</b> - (noun, singular): the original iteration of escape rooms mainly consisting of a boxlike room secured by basic locks. Players solve puzzles to escape and have few props or decorations; the story, if any, is simplistic.</p>",
      "<p><b>Fourth Generation Escape Rooms, &quot;Gen4&quot;</b> - (noun, singular): &quot;smart rooms&quot; that reset themselves and storylines are more deeply connected to gameplay than earlier generations and might be influenced by players' decisions. Some groundbreaking tech like virtual reality, augmented reality, or high-quality special effects might be integrated.</p>",
      "<p><b>Generation / Gen</b> - (adjective): it refers to a classification system that categorizes games based on the technology they utilize, such as Gen 1, Gen 2, and so on. It's important to note that technology is neither inherently positive nor negative in escape rooms. It is one of many tools used to craft immersive experiences.</p>",
      '<p><img src="/assets/blogs/keypad.jpg"/></p>',
      "<p><b>Keypad</b> - (noun, singular): a set of buttons for operating an electronic lock. Usually numerical, but it can also be customized with symbols, letters, etc.</p>",
      "<p><b>Kiosk</b> - (noun, singular): an interactive computer display in a game room used to provide hints and used as a countdown timer and communication device between players and the game master.</p>",
      "<p><b>Latch</b> - (noun, singular): a metal bar with a catch and lever used to fasten a door or a box with a padlock or combination lock, sometimes called a hasp.</p>",
      "<p><b>Mag Lock / Magnetic Lock</b> - (noun, singular) an electronic lock that employs an electromagnet to secure a door or compartment and can be triggered to open through a signal from a button, sensor, or other electronic control mechanisms.</p>",
      '<p><img src="/assets/blogs/padlock.jpg"/></p>',
      "<p><b>Padlock</b> - (noun, singular) a portable key- or combination-activated lock.</p>",
      "<p><b>RFID</b> - (noun, singular) an automatic identification technology that uses radio-frequency electromagnetic fields to identify objects with tags when they are near any reader. It is frequently used in escape rooms to release magnetic locks or trigger other events, often feeling magical.</p>",
      "<p><b>Second Generation Escape Rooms, &quot;Gen2&quot;</b> - (noun, singular): the second iteration of escape rooms. As their popularity grew, they increased in complexity, utilizing new techs like reed switches and IR tech, more elaborate puzzles with fancier locks, and integration of special effects. Set design became more immersive, and games sometimes included passageways or second rooms.</p>",

      "<p><b>Tech</b> - (noun, singular): something that runs on electricity that the players cannot control entirely with an on/off switch.</p>",
      "<p><b>hird Generation Escape Rooms,  &quot;gen3 &quot;</b> - (noun, singular): the third iteration of escape rooms. Focus on imaginative storylines and immersive settings, with more gamemaster interaction. Much more complex systems with interconnected puzzles and tech like RFID sensors, sound detectors, lasers, etc. Dynamic expansion</p>",
      "<p><b>Word Lock</b> - (noun, singular): a lock that is opened with a combination of letters.</p>",
      "</div>",

      '<div class="sbl-block">',
      "<h2>TYPES OF GAMES & BOOKING</h2>",
      '<p><img src="/assets/blogs/types-of-games-and-booking.jpg"/></p>',
      "<p><b>Booking/Reservation</b> - (noun, plural): an appointment (usually set up before the start time) that reserves the date and time you plan to play the escape room.</p>",
      "<p><b>Escape Room Styles</b> - (noun, plural): varieties of escape rooms from different parts of the world. Over the past eight years, the escape room boom in the United States has led styles to intertwine.</p>",
      "<p><b>Game with Actor</b> - (noun, singular): an escape room with an actor present in the room. Sometimes the actor is present during the whole game, and sometimes they appear periodically. Sometimes the actor has storytelling or clue/hint-giving roles; sometimes, they're just there for effect.</p>",
      "<p><b>Mission-based Escape Room</b> - (noun, singular): immersive rooms where players must accomplish a more elaborate task or quest, like obtaining a special item or solving a mystery.</p>",
      "<p><b>Multi-Room</b> - (noun, singular): an escape room that takes place in more than one room, so puzzles and clues are located in at least two rooms and potentially more.</p>",
      "<p><b>One/Single Room</b> - (noun, singular): an escape room that takes place in only one room, so all of the puzzles and clues are within one singular room.</p>",
      '<p><img src="/assets/blogs/online-booking.jpg"/></p>',
      "<p><b>Online Booking</b> - (noun, singular): a reservation made online by a customer.</p>",
      "<p><b>Private Game</b> - (noun, singular): a game limited to the initial group who books it. The same group might be able to add more players if capacity allows, but the game is closed to strangers.</p>",
      "<p><b>Public Game</b> - (noun, singular): a game with open booking, where players are potentially mixed with strangers. For example, suppose a group books a game for three players and chooses the public option. In that case, the remaining slots can be booked by other people.</p>",
      "<p><b>Rebooking</b> - (noun, plural): booking another game after the group has just played.</p>",
      "<p><b>Split Team</b> - (adjective): a style of escape room where the whole team is divided into different gamespaces for some or entire experience. Split team designs are most commonly used as a starting situation, with the team coming together later in the experience.</p>",
      "<p><b>Walk-in Booking</b> - (noun, Singular): a reservation made at the door by a customer without prior booking.</p>",
      "</div>",
      '<div class="sbl-block">',
      "<h2>JOB AND POSITIONS OF ESCAPE ROOM STAFF</h2>",
      '<p><img src="/assets/blogs/job-and-position-of-escape-room-staff.jpg"/></p>',
      "<p><b>Actor</b> - (noun, singular): a person who dresses up and acts as a character to enhance the immersive experience.</p>",
      "<p><b>Escape Room Engineer</b> - (noun, singular): someone who builds and designs electronic systems for escape rooms and can maintain the more sophisticated issues at the facility.</p>",
      '<p><img src="/assets/blogs/escape-room-tech.jpg"/></p>',
      "<p><b>Escape Room Tech</b> - (noun, singular: a maintenance person or engineer who maintains and upkeeps an escape room. Can fix structural damage, electronic issues, regular wear and tear, etc. Sometimes the same person builds props for escape rooms or entire rooms.</p>",
      "<p><b>Game Host</b> - (noun, singular): in more extensive escape room operations, the game host greets groups, briefs them on the rules, and resets games. They do not monitor games.</p>",
      "<p><b>Gamemaster / Host / Game Guide / Cluemaster</b> - (noun, singular): the person responsible for monitoring the in-game experience, providing hints, delivering, and enforcing rules.</p>",

      "</div>",

      '<div class="sbl-block">',
      "<h2>TYPES OF HINTS & HINT RELATED TERMS</h2>",
      '<p><img src="/assets/blogs/types-of-hints.jpg"/></p>',
      "<p><b>Custom Hint</b> - (noun, singular): a personalized hint on the kiosk typed live by the game master.</p>",
      "<p><b>Drag - (verb):</b> to provide a team with so many hints as a gamemaster that the group no longer feels they were responsible for the win. It tends to result from an incompetent team or an incompetent game, and sometimes both.</p>",
      "<p><b>Excessive Hints</b> - (noun, plural): when players request excessive hints because they are inexperienced, lost in the room, etc.</p>",
      "<p><b>Hint levels</b> - (noun, plural): </p>",
      "<ul> ",
      "<li><b>Level 1:</b> A very light hint. The least amount of help possible, offering guidance on where players should focus.</li>",
      "<li><b>Level 2:</b> A light hint which provides a slight nudge in the right direction.</li>",
      "<li><b>Level 3:</b> A medium hint. Usually helps an average group to solve the puzzle.</li>",
      "<li><b>Level 4:</b> A hard hint. Usually helps a group of beginners to solve the puzzle but stops short of providing the complete solution.</li>",
      "<li><b>Level 5:</b> The solution or a significant part of the solution makes it easy for players to develop the complete solution.</li>",

      "</ul>",
      "<p><b>Hint Penalty / Clue Penalty</b> - (noun, singular): the punishment for needing additional information outside regular gameplay. The penalty is often an extra &quot;time&quot; added to the escape time. If a team escapes in 50 minutes but uses a hint, it's counted as if they escaped in 53 minutes. It can sometimes also be an in-game action, such as dancing or singing, that the team must do to get the necessary outside information.</p>",
      '<p><img src="/assets/blogs/hint-system.jpg"/></p>',
      "<p><b>Hint System</b> - (noun, singular): the method by which hints are delivered.</p>",
      "<p><b>Leading Hint</b> - (noun, singular): a hint provided without any request to lead the team in the correct direction. Leading hints are typically given when a team seems lost, frustrated, or has spent significant time attempting to solve a puzzle. It should be simple without containing a solution. They can also be provided to newer players or those who request excessive hints.</p>",
      "<p><b>Microphone Hint</b> - (noun, singular): hints given by the game master via microphone.</p>",
      "<p><b>Picture Hint</b> - (noun, singular): a hint on the kiosk screen displaying a picture for visual aid.</p>",
      "<p><b>Requested Hint</b> - (noun, singular): a hint the team asks for during the game. Requested hints are pre-set in the system and should be granted until that puzzle is solved.</p>",
      "<p><b>Spin</b> - (verb): to stall in an escape room and take the clues in all sorts of outlandish directions instead of taking a hint.</p>",
      "<p><b>Strategic Hint</b> - (noun, singular): a hint used because of deceit to speed up the team's performance.</p>",
      '<p><img src="/assets/blogs/video-hint.jpg"/></p>',
      "<p><b>Video Hint</b> - (noun, singular): hint on the kiosk screen displaying a video of a solution.</p>",
      "<p><b>Voiceover Hint</b> - (noun, singular): an auditory hint read in the voice of the room narrator.</p>",

      "</div>",
      '<div class="sbl-block">',
      "<h2>TYPES OF ESCAPE ROOM PUZZLES</h2>",
      '<p><img src="/assets/blogs/types-of-escape-room-puzzles.jpg"/></p>',
      "<p><b>Aha Puzzle</b> - (noun, singular): this puzzle type presents an initially incomprehensible concept, but once you experience a sudden realization or 'aha moment,' the entire solution to the puzzle becomes obvious instantly.</p>",
      "<p><b>Bonus Content</b> - (noun, plural): puzzles that offer something to the players besides escaping or completing the escape room's primary objective. These side quests can occur alongside the main objective, or completion of the main objective can trigger new objectives. </p>",
      "<p><b>Central Puzzle</b> - (noun, singular): a puzzle into which more puzzles connect, hard to bypass.</p>",
      "<p><b>Communication Puzzle</b> - (noun, singular): a type of escape room puzzle challenge that requires at least two parties to interchange information.</p>",
      "<p><b>Connected Puzzles</b> - (noun, plural): two puzzles connected to each other, either electronically or by logic.</p>",
      "<p><b>Destructible Puzzle</b> - (noun, singular): a puzzle that requires the players to break a prop irreversibly in order to achieve the solution.</p>",
      "<p><b>Hidden Items</b> - (noun, plural): classic &quot;search and find&quot; games.</p>",

      "<p><b>Illusion, Perspective, or Visual Design Games</b> - (noun, plural): puzzles that must be viewed from a specific angle or require focused attention to be seen because they're incorporated into the room's setting, props, or background scenery. </p>",
      "<p><b>Logic Puzzle</b> - (noun, singular): puzzles requiring logic, such as deciphering, etc.</p>",
      "<p><b>Maze Games</b> - (noun, plural): a prop containing a maze the players must solve or an actual maze they must go through themselves.</p>",
      "<p><b>Meta Puzzle</b> - (noun, singular): a puzzle that unites several puzzles into it. A meta puzzle is typically set late in the game. Players must complete a series of other different puzzles before tackling them.</p>",
      "<p><b>Parallel puzzle</b> - (verb): to complete multiple puzzles concurrently with different teammates working on each at the same time. Some escape room design allows this. It can refer to teammates working in parallel in the same gamespace or different gamespaces as part of the same escape room.</p>",
      "<p><b>Skill Puzzle</b> - (noun, singular): puzzles requiring manual dexterity and physical skills.</p>",
      "</div>",
      '<div class="sbl-block">',
      "<h2>MISCELLANEOUS TERMINOLOGY</h2>",
      '<p><img src="/assets/blogs/miscellaneous-terminology.jpg"/></p>',
      "<p><b>Alternative Solution</b> - (noun, singular): an optimal and logical solution that diverges from the puzzle designer's intended solution.</p>",
      "<p><b>Anagram</b> - (noun, singular): a term for rearranging the letters of a word or phrase to form a new term, expression, or phrase is called an anagram. Anagrams are often used in puzzles and word games to provide a challenge and to test one's ability to rearrange letters to form new words.</p>",
      "<p><b>Backseat Solve</b> - (verb): standing behind someone and telling them what to do because you're frustrated that your hands aren't on the puzzle. It is typically discouraged.</p>",
      "<p><b>Backsolve</b> - (verb): to analyze a completed puzzle to deduce the steps taken to arrive at the solution.</p>",
      '<p><img src="/assets/blogs/blacklight.jpg"/></p>',
      "<p><b>Blacklight</b> - (noun, singular): a handheld or stationary light that emits UV radiation, invisible to the human eye. It is a common prop in escape rooms.</p>",
      "<p><b>Blind Choice</b> - (noun, singular): an interactive scenario in which players are required to make a decision, often a moral or ethical one, but are presented with insufficient information or context to arrive at an informed decision.</p>",
      "<p><b>Bottleneck</b> - (noun, singular): a point in the game at which only one puzzle is available to the team resulting in the whole team converging around that single puzzle.</p>",
      '<p><img src="/assets/blogs/braille.jpg"/></p>',
      "<p><b>Braille</b> - (noun, singular): a form of written language for blind people. Different configurations of raised dots represent letters and numbers.</p>",
      "<p><b>Breakage</b> - (noun, singular): any prop that no longer functions as it should due to malfunction, poor design, reckless players, wear, or vandalism.</p>",
      "<p><b>Brute-Force / Guess</b> - (verb): the act of feeding numbers into a lock until it pops. This term can be confusing as it sometimes means &quot;excessive physical force.&quot;</p>",
      "<p><b>Caesar Cipher / Caesarian Shift</b> - (noun, singular): an encryption technique using a substitution cipher in which each letter in the text is replaced by a letter.</p>",
      '<p><img src="/assets/blogs/combination-lock.jpg"/></p>',
      "<p><b>Combination Lock</b> - (noun, singular): a lock that opens when the correct alphabetic, numeric, or symbolic password is entered.</p>",
      "<p><b>Cryptex</b> - (noun, singular): a cylinder with a combination letter lock built as a self-locking mechanism. The concept was adapted from the Dan Brown novel The Da Vinci Code, and it was turned into an actual product by Justin Nevins.</p>",
      "<p><b>Dark Room</b> - (noun, singular): an escape room played in complete darkness. It is often confused with dimly lit rooms.</p>",
      "<p><b>Difficulty by Darkness</b> - (noun, singular): a type of escape room made more challenging by dim, gloomy lighting. It should not be confused with a dark room (see above.)</p>",
      "<p><b>Do Not Touch Sticker</b> - (noun, singular): a sticker or piece of tape attached to props and pieces in the set that are &quot;out of play.&quot; The definition of &quot;out of play&quot; varies among escape rooms.</p>",
      "<p><b>Easter Egg</b> - (noun, singular): an unexpected feature in an escape room included as a joke or a bonus.</p>",
      "<p><b>Errol</b> - (verb): take off one's shoes inside an escape room for comfort and focus.</p>",
      '<p><img src="/assets/blogs/escake.jpg"/></p>',
      "<p><b>Escake</b> - (noun, singular): a delicacy for celebration used to mark the completion of an escape room, traditionally a cake.</p>",
      "<p><b>Escape Room / Escape Game / Room Escape</b> - (noun, singular): an activity in which a team works together to uncover and tackle puzzles, assignments, and obstacles that don't require any prior knowledge, all while being physically present at a location, with the aim of achieving a specific objective within a designated time frame.</p>",
      "<p><b>Escape Room Logic</b> - (noun, singular): a solution to a puzzle that is logical and consistent when considering the gameplay mechanics but may not necessarily align with the storyline or narrative of the game. E.g., You're a fugitive from the police, looking for the information that will clear your name, but why are you counting the cups in the cabinet to get a lock combination?</p>",
      "<p><b>Filler / Junk / Noise / Fluff</b> - (noun, plural): subpar escape room content (puzzles, props, or story content) deliberately included to lengthen the game experience.</p>",
      "<p><b>Frontsolve / Forward Solve</b> - (verb): to solve a puzzle as intended by the designer.</p>",
      "<p><b>Game Flow</b> - (noun, singular): game flow refers to the linkage or continuity between game elements or puzzles. It encompasses the overall experience of a game, including how one puzzle leads to another or how a meta-puzzle fits into the larger picture. Game flow can be visualized as a diagram or chart that outlines the progression of the escape room.</p>",
      "<p><b>Gamespace / Set</b> - (noun, singular): the gaming environment.</p>",
      "<p><b>Ghost Puzzle / Residue Puzzle</b> - (noun, singular): these are artifacts of a past version of a puzzle that are no longer relevant to the game's current state, yet they remain within the clues, potentially causing confusion and hindering the players' progress.</p>",
      "<p><b>Glyph</b> - (noun, singular): a symbol that could mean something.</p>",
      "<p><b>Head to Head / Competitive Games</b> - (adjective): this pertains to a setup where two identical escape rooms are available for play at the same time, allowing teams to compete against each other in a race-like fashion. In some cases, there may be opportunities for interaction between the teams during the game.</p>",
      "<p><b>Human Circuit</b> - (adjective): describes a puzzle requiring players to form a human chain between metal props to connect a circuit triggering an event.</p>",
      '<p><img src="/assets/blogs/individual-role-individual-goal.jpg"/></p>',
      "<p><b>Individual Role / Individual Goal</b> - (noun, singular): a type of escape room where the players are each assigned characters or objectives outside the team objective, sometimes both. It can put the players in a competition, but it doesn't necessarily have to be.</p>",
      "<p><b>Inescapable Room with an Error Margin</b> - (noun, singular): any escape room with less than a 5% escape rate.</p>",
      "<p><b>Informed Choice</b> - (noun, singular): an interaction where players must make a decision (commonly an ethical decision) based on sufficient information to understand the context of their choice.</p>",
      "<p><b>Interaction</b> - (noun, singular): a designed action within the game.</p>",
      '<p><img src="/assets/blogs/key-for-key.jpg"/></p>',
      "<p><b>Key for Key</b> - (noun, singular): a key locked up behind another key lock.</p>",
      "<p><b>Kimmy Schmidt Crank</b> - (noun, singular): a crank that must be regularly turned to keep the power on.</p>",
      "<p><b>Leaderboard</b> - (noun, singular): a ranking of the best times people completed the room. Leaderboards encourage groups to beat a particular time or score.</p>",
      "<p><b>Live</b> - (adjective): describes an element that you know will open or move in the future.</p>",
      "<p><b>Lock</b> - (noun, singular): a sealed fastening that requires a physical key or combination of numbers, letters or directions to unlock.</p>",
      "<p><b>Lock Guy / Lock Girl / Locksmith</b> - (noun, singular): the one teammate who always wants to open the lock or input the combination. Sometimes, players who don't feel they can contribute to solving the puzzles and opening things make them feel like the hero.</p>",
      "<p><b>Lock Picking / Lock Exploiting - (verb)</b>: using the design flaw within a locking mechanism to open a lock without solving the corresponding puzzle.</p>",
      '<p><img src="/assets/blogs/lockout-safe.jpg"/></p>',
      "<p><b>Lockout Safe</b> - (noun, singular): a container or storage unit equipped with a combination lock that temporarily locks out if multiple incorrect codes are entered. Escape room enthusiasts typically disapprove of lockout safes.</p>",
      "<p><b>Lock Whisperer</b> - (noun, singular): the teammate who always gets the locks open. They have a special touch.</p>",
      "<p><b>Magnet Maze</b> - (noun, singular): this is a common escape room device in which a small item, often a key, is located behind an obstruction and must be retrieved using a magnet.</p>",
      "<p><b>Mission, Objective, or Quest - (noun, singular)</b>: in mission-based games, the goal of the game or what players need to accomplish.</p>",
      "<p><b>Morse Code</b> - (noun, singular): a code in which combinations of long and short light or sound signals represent letters. The original purpose of the Morse Code was to facilitate long-distance communication rather than obscuring messages.</p>",
      "<p><b>Muggles / Rookies / First-time Players/ Newbies</b> - (noun, plural): the previously uninitiated.</p>",
      "<p><b>Non-Binary Win Condition</b> - (noun, singular): this refers to an escape room that does not have a binary win-or-lose outcome but instead has varying degrees or types of success.</p>",
      "<p><b>Non-Playing Character (NPC)</b> - (noun, singular): any person inside the game that is not a player trying to solve clues. It could include a game master or an actor who is part of the experience, such as the zombie chained to the wall in Trapped in a Room With a Zombie or the Bogeyman in Bogeyman.</p>",
      "<p><b>Number Soup</b> - (noun, singular): an escape room where your brain is overwhelmed with so many numbers, combination locks, and a lack of strong correlations between the numbers and the locks.</p>",
      "<p><b>One-time Use</b> - (adjective): describes props that will only contribute to a single puzzle solution.</p>",
      "<p><b>On-ramp</b> - (noun, singular): the first puzzle in the escape room; it should generally stand out and be approachable</p>",
      "<p><b>Order Preservation</b> - (adjective): these puzzles become unsolvable if players alter certain items' initial position or arrangement.</p>",
      '<p><img src="/assets/blogs/over-locked-lock-orgy.jpg"/></p>',
      "<p><b>Over-locked / Lock Orgy</b> - (adjective/noun): describes a single item that is secured with too many locks.</p>",
      "<p><b>Paper Puzzle / Homework Puzzle</b> - (noun, singular): a puzzle that does not require the gameset and can be solved anywhere.</p>",
      "<p><b>Pigpen / Masonic Cypher</b> - (noun, singular): an 18th-century substitution cipher made by the freemasons that exchange letters for geometric symbols that are grid fragments.</p>",
      "<p><b>Pipeline / High Throughput Model</b> - (noun, singular): refers to an escape room where multiple teams participate simultaneously. Each team is in a separate room and progresses through the experience independently, without backtracking or encountering other groups.</p>",
      "<p><b>Plaintext</b> - (noun, singular): any text that is not encrypted.</p>",
      "<p><b>Play the Blame Game</b> - (verb): to blame a failed escape game on the puzzles that make sense to most players just because one is being salty about not escaping.</p>",
      '<p><img src="/assets/blogs/players.jpg"/></p>',
      "<p><b>Players</b> - (noun, plural): a group attempting to solve puzzles to complete a mission and escape the room.</p>",
      "<p><b>Process</b> Puzzle / Taskwork - (noun, singular): describes a type of puzzle where the solution requires understanding a previously unclear concept and performing additional work to derive the correct answer.</p>",
      "<p><b>Psychic</b> - (noun, singular): a &quot;psychic&quot; player is someone who remains stationary in front of a single lock throughout the game, attempting to guess the combination rather than engaging with the rest of the game. Despite their efforts, the psychic never manage to guess the correct combination.</p>",
      "<p><b>Puppet</b> - (verb): refers to enlisting the help of an additional person who is already familiar with the solution to serve as an extra pair of hands in an escape room. Solo players or small teams often use this technique to complete a challenge designed for larger groups. A gamemaster puppet may enter the room and follow the instructions of the player(s) to help them complete the multiplayer challenge.</p>",
      "<p><b>Puzzle</b> Snatching / Puzzle Yanking - (verb): taking or stealing a puzzle or component of a puzzle from another player is generally viewed as unsportsmanlike behavior.</p>",
      '<p><img src="/assets/blogs/randoms.jpg"/></p>',
      "<p><b>Randoms</b> - (noun, plural): individuals randomly assigned to be part of your team in an escape room through a public ticketing booking system. They are essentially strangers whom you have not previously met.</p>",
      "<p><b>Recap / Thought Journey</b> - (noun, singular): refers to a description or explanation, usually provided mid-game or towards the end of the game, to help teammates get back in sync after a puzzle or series of puzzles has been successfully solved.</p>",
      "<p><b>Runbook</b> - (noun, singular): refers to a prop or device within an escape room that provides a comprehensive list of the steps the team must follow to escape successfully. It may outline all or many of the necessary tasks and actions that need to be completed.</p>",
      "<p><b>Replay Value</b> - (noun, singular): a game's ability to be played by the same person after it's been played once. Games with open endings have higher replay values than those with only one ending.</p>",
      '<p><img src="/assets/blogs/safe.jpg"/></p>',
      "<p><b>Safe</b> - (noun, singular): a box or cabinet with a keypad or combination locking mechanism.</p>",
      "<p><b>Sandbag</b> - (verb): refers to intentionally limiting one's contribution or level of participation to allow less experienced players a more enjoyable and fulfilling experience. It can help prevent more experienced players from dominating the game and allow everyone to contribute and have fun.</p>",
      "<p><b>Search / Hunt / Scavenge</b> - (verb): to look for hidden clues within the game space.</p>",
      "<p><b>Search Fail</b> - (noun, singular): failure to find a clue hidden within the game space.</p>",
      "<p><b>Seizure Mode</b> - (noun, singular): refers to a mode on certain handheld flashlights where the light flashes rapidly and continuously. This mode differs from a weak or flickering flashlight as it is intentionally designed to produce a strobing effect.</p>",
      "<p><b>Self-resetting / Automatically-resetting</b> - (adjective): refers to an escape room that can be played again immediately without requiring a gamemaster to reset the room. It is often associated with &quot;pipelining,&quot; a process in which multiple groups of players are moved through the same escape room one after another, with minimal downtime in between. It allows maximum efficiency and throughput, making it possible for more players to experience the room in less time.</p>",
      "<p><b>Semaphore</b> - (noun, singular): a system of communication using visual signals, typically flags or lights, in which the position of the arms or flags represents letters or numbers according to a code. In escape rooms, a semaphore is often used as a cipher to encode messages or clues. Players must understand the code and decipher the message to progress through the game.</p>",
      "<p><b>Set Piece</b> - (noun, singular): a self-contained segment of the gamespace.</p>",
      '<p><img src="/assets/blogs/signpost.jpg"/></p>',
      "<p><b>Signpost</b> - (verb): to direct players to what they're meant to be working on through subtle in-game cluing</p>",
      "<p><b>Sudden Death</b> - (adjective): describes an escape room where you can take an action that results in losing before the game clock runs out. e.g., cutting the wrong wire on the bomb.</p>",
      "<p><b>Surprise Satanism</b> - (noun, singular): a genre of escape room where the initial gamespace is comfortable and welcoming, but a later gamespace reveals blood, guts, pentagrams, or anything unexpectedly sinister.</p>",
      "<p><b>Time Remaining</b> - (adjective): the amount of time left in which you have to complete the puzzles and escape before your experience is over.</p>",
      "<p><b>Trap Door / Hidden Door/ Hatch</b> - (noun, singular): a hidden or obscured doorway.</p>",
      "<p><b>Used Pile / Done Pile / Discard Pile</b> - (noun, singular): a pile of single-use props already used. Players create used piles to keep organized.</p>",
      "<p><b>Vouched-for Randoms</b> - (noun, plural): randoms you have yet to meet but you are less wary about playing with due to their connections to the escape room community.</p>",
      "<p><b>Wear</b> - (noun, singular): marks or changes to a prop due to regular use or handling. Wear frequently exposes solutions. e.g., &quot;There is wear on Boston on this map, and it must be the answer.&quot;</p>",
      '<p><img src="/assets/blogs/wordlock.jpg"/></p>',
      "<p><b>Word Lock</b> - (noun, singular): a lock that is opened with a combination of letters.</p>",
      "</div>",
    ],
    relatedblogdata: [
      {
        id: "1",
        slug: "what-kind-of-leaf-is-this",
        ftimg: "/assets/blogs/blog-ft.jpg",
        title: "What kind of leaf is this?",
        blogdesc:
          "You'd better baylieve that the game is going to get harder from here! You'd better baylieve that the game is going to get harder from here! You'd better",
        authimg: "/assets/blogs/blog-auth1.png",
        authname: "by Brian Capps",
        blogcategory: [
          {
            id: "1",
            name: "Escape Room",
            slug: "escape-room",
          },
          {
            id: "2",
            name: "Team Building",
            slug: "team-building",
          },
        ],
        lastupdate: "April 02, 2022",
      },
      {
        id: "2",
        slug: "what-kind-of-leaf-is-this",
        ftimg: "/assets/blogs/blog-ft.jpg",
        title: "1. What kind of leaf is this What kind of leaf is this?",
        blogdesc:
          "You'd better baylieve that the game is going to get harder from here! You'd better baylieve that the game is going to get harder from here! You'd better",
        authimg: "/assets/blogs/blog-auth1.png",
        authname: "by Brian Capps",
        blogcategory: [
          {
            id: "1",
            name: "Escape Room",
            slug: "escape-room",
          },
          {
            id: "2",
            name: "Team Building",
            slug: "team-building",
          },
        ],
        lastupdate: "May 18, 2022",
      },
    ],
  },
};
